[2025-04-21T07:46:46.043+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-21T07:46:46.056+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_data_etl_dbt.extract_and_load manual__2025-04-21T07:46:43.476610+00:00 [queued]>
[2025-04-21T07:46:46.062+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_data_etl_dbt.extract_and_load manual__2025-04-21T07:46:43.476610+00:00 [queued]>
[2025-04-21T07:46:46.062+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-04-21T07:46:46.070+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): extract_and_load> on 2025-04-21 07:46:43.476610+00:00
[2025-04-21T07:46:46.078+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=4690) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-21T07:46:46.080+0000] {standard_task_runner.py:72} INFO - Started process 4698 to run task
[2025-04-21T07:46:46.079+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'stock_data_etl_dbt', 'extract_and_load', 'manual__2025-04-21T07:46:43.476610+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/Stock_built_ELT.py', '--cfg-path', '/tmp/tmpqluhkoy3']
[2025-04-21T07:46:46.082+0000] {standard_task_runner.py:105} INFO - Job 27: Subtask extract_and_load
[2025-04-21T07:46:46.143+0000] {task_command.py:467} INFO - Running <TaskInstance: stock_data_etl_dbt.extract_and_load manual__2025-04-21T07:46:43.476610+00:00 [running]> on host 712e28762a67
[2025-04-21T07:46:46.201+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stock_data_etl_dbt' AIRFLOW_CTX_TASK_ID='extract_and_load' AIRFLOW_CTX_EXECUTION_DATE='2025-04-21T07:46:43.476610+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-21T07:46:43.476610+00:00'
[2025-04-21T07:46:46.202+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-21T07:46:46.778+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-04-21T07:46:46.779+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-6.12.5-linuxkit-aarch64-with-glibc2.36
[2025-04-21T07:46:46.780+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-04-21T07:46:46.781+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-04-21T07:46:47.569+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-04-21T07:46:47.685+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-04-21T07:46:47.782+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-04-21T07:46:47.900+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-04-21T07:50:32.928+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-04-21T07:50:32.934+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-21T07:50:32.981+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-21T07:50:32.981+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=stock_data_etl_dbt, task_id=extract_and_load, run_id=manual__2025-04-21T07:46:43.476610+00:00, execution_date=20250421T074643, start_date=20250421T074646, end_date=20250421T075032
[2025-04-21T07:50:33.032+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-21T07:50:33.084+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-21T07:50:33.085+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
